services:
  postgres-test:
    image: postgres:18.3-alpine3.23
    restart: always
    environment:
      POSTGRES_DB: test_db
      POSTGRES_PASSWORD: root
    ports:
    - '5432:5432'
    volumes:
    - postgres_test_data:/var/lib/postgres
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: felipe@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '8080:80'
    volumes:
      - pgadmin_test_data:/var/lib/pgadmin
    networks:
      - default
    depends_on:
      - postgres-test

volumes:
  pgadmin_test_data:
  postgres_test_data:

networks:
  default:
    name: postgres_test_network