services:
  postgres-test:
    image: postgres:18.3-alpine3.23
    restart: always
    environment:
      POSTGRES_PASSWORD: sdcfasdcads%d
      POSTGRES_DB: tests
    ports:
    - '5432:5432'
    volumes:
    - postgres-test:/var/lib/postgres
    
volumes:
  postgres-test: